In [1]:
import pandas as pd

In [2]:
ex=pd.read_excel('events/cf25dat.xlsx')

In [3]:
gx=pd.read_csv('20250623 - Detailed Schedule - v9(FINAL).csv')

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69900/1711732104.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  gx=pd.read_csv('20250623 - Detailed Schedule - v9(FINAL).csv')

In [4]:
g=gx.dropna(subset=['EasyChair'])

In [5]:
absin=pd.read_csv('CAADFutures_abstractin.csv')

In [6]:
putabs=dict(zip(absin['#'],absin['Abstract']))

In [7]:
g['Date']=g['FILTER OPTIONS.1']

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69900/1342371881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['Date']=g['FILTER OPTIONS.1']

In [9]:
topicmape=dict(zip(g['EasyChair'],g['session title']))
sessimape=dict(zip(g['EasyChair'],g['session code']))

In [57]:
sessimape

{238: 'S-S1',
 349: 'S-S1',
 36: 'S-S1',
 5: 'P-A1',
 46: 'P-A1',
 240: 'P-A1',
 453: 'P-A1',
 169: 'P-B1',
 41: 'P-B1',
 255: 'P-B1',
 217: 'P-B1',
 141: 'P-B1',
 87: 'P-C1 ',
 149: 'P-C1 ',
 252: 'P-C1 ',
 357: 'P-C1 ',
 222: 'P-C1 ',
 447: 'P-D1',
 48: 'P-D1',
 162: 'P-D1',
 187: 'P-D1',
 127: 'P-D1',
 126: 'S-1',
 134: 'S-1',
 135: 'P-A3',
 151: 'S-1',
 33: 'S-2',
 426: 'S-2',
 196: 'S-2',
 148: 'S-S2',
 55: 'S-S2',
 329: 'S-S2',
 262: 'S-S2',
 299: 'P-A2',
 278: 'P-A2',
 29: 'P-A2',
 121: 'P-A2',
 71: 'P-A2',
 45: 'P-B2',
 150: 'P-B2',
 304: 'P-B2',
 456: 'P-B2',
 59: 'P-B2',
 34: 'P-C2',
 155: 'P-C2',
 221: 'P-C2',
 339: 'P-C2',
 408: 'P-C2',
 206: 'P-D2',
 74: 'P-D2',
 137: 'P-D2',
 180: 'P-D2',
 210: 'S-S2',
 440: 'S-S2',
 431: 'S-S2',
 314: 'S-S2',
 50: 'S-3',
 198: 'S-3',
 250: 'S-3',
 132: 'S-4',
 193: 'S-4',
 386: 'S-4',
 178: 'S-4',
 444: 'S-S4',
 403: 'S-S4',
 253: 'S-S4',
 80: 'P-A3',
 145: 'P-A3',
 19: 'P-A3',
 457: 'P-A3',
 68: 'P-B3',
 276: 'P-B3',
 379: 'P-B3',
 428: 'P-B3',
 111: 'P-B3',
 79: 'P-C3',
 313: 'P-C3',
 133: 'P-C3',
 395: 'P-C3',
 114: 'S-S5',
 231: 'S-S5',
 230: 'S-S5',
 82: 'CI',
 330: 'CI',
 389: 'CI',
 427: 'CI',
 445: 'CI',
 458: 'CI'}

In [ ]:
timemape=dict(zip(g['EasyChair'],g['Time']))

In [17]:
idex=ex['ID'].unique()

In [16]:
g['EasyChair']=g['EasyChair'].astype(str).replace('[','').str.replace(']','').str.strip().str.replace('[','')

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69900/75282077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['EasyChair']=g['EasyChair'].astype(str).replace('[','').str.replace(']','').str.strip().str.replace('[','')

In [18]:
g['EasyChair']=g['EasyChair'].astype(int)

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69900/705830128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['EasyChair']=g['EasyChair'].astype(int)

In [19]:
datemape=dict(zip(g['EasyChair'],g['Date']))
timemape=dict(zip(g['EasyChair'],g['Time']))

In [33]:
[c for c in g['EasyChair'].unique() if c not in idex]

[457, 82, 330, 389, 427, 445, 458]

In [34]:
[c for c in idex if c not in g['EasyChair'].unique()]

[214, 376, 283, 27]

In [40]:
ex=ex.loc[~ex['ID'].isin([214, 376, 283, 27])]

In [128]:
en=ex[['ID','Title','Authors','Final Topic','Session','Abstract']]
en.reset_index(inplace=True)

In [129]:
# absin.loc[absin['#']==457]

In [130]:
# en.head(2)

In [131]:
# topicmape[238]

In [132]:
ct=81
for i in [457, 82, 330, 389, 427, 445, 458]:
    try:
        id,aut,title,subs,typesub,timesub,abs=absin.loc[absin['#']==i].values[0]
        en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
    except:
        print(i)
        tnt=g[g['EasyChair']==i]
        en.loc[87]=87+4,tnt['EasyChair'].values[0],tnt['title'].values[0],tnt['authors'].values[0],tnt['session title'].values[0],tnt['session code'].values[0],None
    ct +=1

458

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_69328/3367273670.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[87]=87+4,tnt['EasyChair'].values[0],tnt['title'].values[0],tnt['authors'].values[0],tnt['session title'].values[0],tnt['session code'].values[0],None

In [133]:
en.loc[en['Final Topic'].isna(),'Final Topic']='Catalytic Interface'
# en.loc[en.tail(6).index,'Final Topic']='Catalyi

In [135]:
absin

,#,Authors,Title,File Submission,submission type,Time,Abstract
0,5,"Yanting Shen, Mengqing Yu, Chenyu Huang and Ji...",Superiority of High-Dimensional Latent Variabl...,✔,Regular Paper,"Sep 10, 17:16",Quantitative descriptions of urban morphology ...
1,19,"Tinghao Feng, Yulu Zhang, Xinhui Xu, Zhengchen...",Integrating Regulatory Compliance In AI-Assist...,✔,Regular Paper,"Sep 13, 15:09",In the new era of human-computer interaction (...
2,27,"Shenzhou Dai, Sihang Liu, Haojun Wang, Yulin C...",A Full-Process Digital Method for Recursive Ge...,✔,Regular Paper,"Sep 15, 17:12","The commercial wood processing industry, drive..."
3,29,"Hang Xu, Chengxuan Li, Timur Dogan and Patrick...",Understand Urban Building Energy Consumption w...,✔,Regular Paper,"Sep 16, 02:20",Urban decarbonization is a critical goal in ad...
4,30,"Fang-Che Cheng, Henriette Bier, Ningzhu Wang a...",Review of Advances in the Robotization of Timb...,✔,Regular Paper,"Sep 16, 07:55",Robotic timber construction has advanced signi...
...,...,...,...,...,...,...,...
159,452,"Zhining Wang, Ningyuan Wang, Yue Chen and Zhe Guo",Research on Modular Generation and Constructio...,✔,Regular Paper,"Oct 08, 10:38",The construction logic of traditional dougong ...
160,453,Chee Meng Chan and Frederick Kim,Perceptual Urban Form,✔,Regular Paper,"Oct 09, 03:26","Enabled by growing repositories of urban data,..."
161,454,"Taiyang Wang, Peng Luo and Rudi Stouffs",The optimization of visual perception factors ...,✔,Regular Paper,"Oct 09, 09:53","In the realm of public health studies, the spo..."
162,456,"Li Zhang, Jiawei Wang, Zhicheng Wang, Yuetong ...",Evaluation Method of AI-Generated Architectura...,✔,Regular Paper,"Oct 10, 05:50","Abstract. In recent years, Generative Artifici..."
163,457,"Matthias Hornung, Markus Renner, Diellza Elsha...",Augmenting IFC-Based BIM Models for Graph Neur...,✔,Regular Paper,"May 15, 09:01",Building Information Modeling (BIM) and Indust...

In [139]:
# en.loc[87,'Abstract']=putabs[458]

In [140]:
# putabs[458]

In [141]:
# tnt=g[g['EasyChair']==458]
# en.loc[87]=87+4,tnt['EasyChair'],tnt['title'],tnt['a

In [63]:
tn=absin.loc[absin['#']==i].values

In [65]:
tn[0][0]

457

In [97]:
g[g['EasyChair']==i].values

array([['Catalytic Interfaces', '7/4/2025', '16:50 - 17:10', 'CI',
        'Catalytic Interfaces Presentation', nan,
        'CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDING MASSING AND AUTOMATED COMPLIANCE\n',
        'Tejas Chavan, Houssame E. Hsain, Camiel Weijenberg and Sayjel V. Patel',
        458, nan, nan, '16:50 - 17:10', '[ 458 ]',
        'CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDING MASSING AND AUTOMATED COMPLIANCE\nBy Tejas Chavan, Houssame E. Hsain, Camiel Weijenberg and Sayjel V. Patel',
        nan, nan, '7/4/2025']], dtype=object)

In [104]:
tnt['EasyChair'].values[0]

458

In [15]:
ex['ID']

0     403
1     114
2     238
3     231
4     444
     ...
83    330
84    389
85    427
86    445
87    458
Name: ID, Length: 88, dtype: int64

In [20]:
ex['Date']=ex['ID'].map(datemape)

In [21]:
ex['Time']=ex['ID'].map(timemape)

In [22]:
ex

,Unnamed: 0,index,ID,Title,Authors,Final Topic,Session,Abstract,Date,Time
0,0,0,403,Text-to-Siheyuan: LLM-based Multi-Agent Proced...,"Zixi Zhang, Wenshuo Zhang and Runjia Tian",PROMPTING ARCHITECTURE,S-S5,Rule-Based Procedural Content Generation (PCG)...,7/4/2025,10:50 - 11:05
1,1,1,114,ConStructGNN: A Graph Neural Network Framework...,"Quan Zhou, Yize Li, Zejian Li and Immanuel Koh",ARCHITECTURAL COMPUTING & REASONING,S-S5,"This study proposes a workflow, ConStructGNN, ...",7/4/2025,13:45 - 14:00
2,2,2,238,Design Validation for Robotic Fabrication: A M...,Pok Yin Victor Leung and Yijiang Huang,INTELLIGENT ROBOTIC ASSEMBLY,S-S1,The use of robotics in construction offers tra...,7/2/2025,11:25 - 11:40
3,3,3,231,Reading Between the Lines: Bridging AI and Arc...,"Marija Mateljan, Seyran Khademi and Georg Vrac...",ARCHITECTURAL COMPUTING & REASONING,S-S5,Architectural drawings are powerful tools for ...,7/4/2025,14:00 - 14:15
4,4,4,444,Interactive BIM Modelling Assistant with Multi...,"Chao Tang, Kam-Ming Mark Tam and Christiane Ma...",PROMPTING ARCHITECTURE,S-S5,The integration of Geographic Information Syst...,7/4/2025,10:35 - 10:50
...,...,...,...,...,...,...,...,...,...,...
83,83,87,330,Rethinking Participatory Architectural Design:...,"Weiheng Hu, Yuval Kahlon, Momoko Nakatani and ...",Catalytic Interface,CI,Participatory Architectural Design (PAD) offer...,7/4/2025,15:30 - 15:50
84,84,88,389,(CI) Augmentation in Design and Fabrication: E...,"Igor Pantic, Soomeen Hahm, Peter Búš and Zhiyo...",Catalytic Interface,CI,The future of architectural practice is increa...,7/4/2025,15:50 - 16:10
85,85,89,427,Toward AIXR: Designing a Framework for AI-Info...,"Matias del Campo, Joseph Kenny, Eleni Vasiliki...",Catalytic Interface,CI,"This paper presents AIXR, a framework for arti...",7/4/2025,16:10 - 16:30
86,86,90,445,Buildings as Symbiotic Systems: Cybernetic Ada...,"Davide Schaumann, Andrew Vande Moere, Yuval Ka...",Catalytic Interface,CI,Contemporary architectural design increasingly...,7/4/2025,16:30 - 16:50
87,87,91,458,CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDIN...,"Tejas Chavan, Houssame E. Hsain, Camiel Weijen...",Catalytic Interface,CI,TBU,7/4/2025,16:50 - 17:10

In [24]:
ex.to_excel('events/cf25dat.xlsx')